sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
- openjdk11

cache:
  directories:
  - $HOME/.m2

env:
  - DOCKER_IMAGE=gs8150/prva:latest
  - DOCKER_REPO=gs8150/test

script:
  - mvn clean package -U
  - cd prva
  - docker build ./ -t "$DOCKER_IMAGE"
after_success:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker push "$DOCKER_REPO"
