sudo: required

services:
  - docker

language: java
dist: trusty

jdk:
- openjdk11

cache:
  directories:
  - $HOME/.m2

script:
  - mvn clean package -U
  - cd prva
  - docker build -t gs8150/prva:latest .
after_success:
  - docker login --username "$ACCOUNT" -password "$PASSWORD"
  - docker push gs8150/prva:latest
