kumuluzee:
  name: rso-prva
  env:
    name: dev
  version: 1.0.1
  server:
    base-url: http://localhost:8081
    http:
      port: 8081
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 120
    ping-interval: 100
app-properties:
  external-services:
    enabled: false
    baseUrl: http://localhost:8081