kumuluzee:
  name: rso-druga
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://172.17.0.1:8080
    http:
      port: 8080
  config:
    etcd:
      hosts: http://192.168.1.135:2379
  discovery:
    etcd:
      hosts: http://192.168.1.135:2379
    ttl: 20
    ping-interval: 15
