kumuluzee:
  name: rso-druga
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  config:
    etcd:
      hosts: http://localhost:2379
  discovery:
    etcd:
      hosts: http://localhost:2379
    ttl: 120
    ping-interval: 100
app-properties:
  external-services:
    enabled: false
    baseUrl: http://localhost:8082